version: '3.9'

services:
  nextjs-react-complete-guide:
    build:
      context: ../../
      dockerfile: docker/production/Dockerfile
    image: nextjs-react-complete-guide-production:latest
    ports:
      - '3000:3000'
